"""setting up heroku

Revision ID: 0335f46f0573
Revises: 1b3962442bff
Create Date: 2018-10-25 13:29:57.012802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0335f46f0573'
down_revision = '1b3962442bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
