"""initialr

Revision ID: 195e87476ace
Revises: d17a4b451a31
Create Date: 2018-10-20 08:20:52.008637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '195e87476ace'
down_revision = 'd17a4b451a31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
