"""it w will

Revision ID: 1b3962442bff
Revises: 9ca1e7d8cd9a
Create Date: 2018-10-20 10:48:03.586334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b3962442bff'
down_revision = '9ca1e7d8cd9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_details', 'year',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=8),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_details', 'year',
               existing_type=sa.String(length=8),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
