"""initialr

Revision ID: 1bd9d8879cf0
Revises: 24186a96bdb9
Create Date: 2018-10-20 08:53:35.115327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd9d8879cf0'
down_revision = '24186a96bdb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
