"""initialr

Revision ID: 24186a96bdb9
Revises: 195e87476ace
Create Date: 2018-10-20 08:50:44.990013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24186a96bdb9'
down_revision = '195e87476ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
