"""it worked. second time

Revision ID: 50ccf50eeff1
Revises: 9470daaf8b89
Create Date: 2018-10-20 09:12:03.099709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50ccf50eeff1'
down_revision = '9470daaf8b89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_details', 'year',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_details', 'year',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    # ### end Alembic commands ###
