"""initialqq

Revision ID: 6a046309d883
Revises: 31d08218ea82
Create Date: 2018-10-20 07:58:25.859054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a046309d883'
down_revision = '31d08218ea82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
