"""it worked. second te

Revision ID: 9ca1e7d8cd9a
Revises: 50ccf50eeff1
Create Date: 2018-10-20 10:42:18.161274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca1e7d8cd9a'
down_revision = '50ccf50eeff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
