"""initialq

Revision ID: aad35f9c0bc8
Revises: 6a046309d883
Create Date: 2018-10-20 08:11:54.268904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aad35f9c0bc8'
down_revision = '6a046309d883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
