"""initialr

Revision ID: d17a4b451a31
Revises: aad35f9c0bc8
Create Date: 2018-10-20 08:17:17.003613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd17a4b451a31'
down_revision = 'aad35f9c0bc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
